baseURL = "/"
languageCode = "en-us"
title = "Square Goldfish"
themesDir = "themes"
theme = "squaregoldfish"
disableKinds = ["taxonomy","taxonomyTerm"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 2

[[menu.main]]
    name = "3D Printing"
    url = "/3dprinting/"
    weight = 3

[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 4

[[menu.main]]
    name = "Programming"
    url = "/programming/"
    weight = 5

[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 6

[params]
  google_analytics_id=""
  homepage_button_link = ''
  homepage_button_text = ''
  homepage_intro = 'The random jottings of a geometrically precise aquatic lifeform'
  homepage_image = ''
  mainSections = ["software", "programming", "photos", "3dprinting", "links"]

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = ""
    meta_og_title = "Square Goldfish"
    meta_og_type = "website"
    meta_og_url = "https://www.squaregoldfish.co.uk"
    meta_og_description = "The random jottings of a geometrically precise aquatic lifeform"

  [params.logo]
      mobile = "/images/fish.png"
      standard  = "/images/fish.png"
